language:
    - objective-c

before_install:
    - brew update

install:
    - brew install cmake

script:
    - mkdir _builds
    - cd _builds
    - cmake -GXcode ..
    - xcodebuild -sdk iphonesimulator -arch i386
